project_id = "jlbftyjewxgetxcihban"

[functions.enhanced-pdf-generator]
verify_jwt = false

[functions.process-assessment]
verify_jwt = false

[functions.storage-monitor] 
verify_jwt = false

[functions.send-deletion-notification]
verify_jwt = true

[functions.create-test-access]
verify_jwt = true